syntax = "proto3";

import "scalapb/scalapb.proto";

option java_multiple_files = true;

package com.domain.chat.session.cassandra.commands;

option (scalapb.options) = {
  scope: PACKAGE
  flat_package: true
  lenses: true
  enum_value_naming: CAMEL_CASE
  enum_strip_prefix: true
  preserve_unknown_fields: false
  scala3_sources: true
};

message CassandraCmd {

  oneof sealed_value {
    GetLatestBucketName getLastBucket = 1;
  }
}

message GetLatestBucketName {
  string chat = 1 [(scalapb.field).type = "shared.Domain.ChatName"];
}
